# NeoCase Configuration v1.0.0

# Плейсхолдеры
# {amount} - Количество ключей
# {case} - Название кейса
# {player} - Никнейм игрока
# {item} - Предмет

# База данных
database:
  # Включена ли База Данных
  enabled: false
  # Адрес Базы данных
  host: "localhost"
  # Порт подключения к Базе данных
  port: 3306
  # Название Базы данных
  database: "neocase"
  # Пользователь для подключения к Базе данных
  username: "root"
  # Пароль к Базе данных
  password: ""
  # Префикс для таблиц в Базе данных (нужен если несколько серверов используют одну БД)
table-prefix: "neocase_"

# Настройки
settings:
  # Стандартная анимация
  default-animation: "roulette"
  # Сообщение о выигрыше
  broadcast-wins: true
  # Звуковые эффекты
  sound-effects: true
  # Требовать ключ
  require-keys: true

# Сообщения
messages:
  # Нет прав
  no-permission: "&cУ вас нет прав!"
  # Кейс не найден
  case-not-found: "&cКейс не найден!"
  # Нет ключей
  no-keys: "&cУ вас нет ключей для этого кейса!"
  # Получение ключей
  key-received: "&aВы получили &e{amount} &aключей для кейса &6{case}&a!"
  # Выдача ключей
  key-given: "&aВы выдали &e{amount} &aключей кейса &6{case} &aигроку &e{player}&a!"
  # Открытие кейса
  case-opening: "&6Открываем кейс..."
  # Выигрыш
  case-won: "&aПоздравляем! Вы выиграли: &e{item}&a!"